import z from "zod";
import path from "path";
import * as fs from "fs/promises";
import PptxGenJS from "pptxgenjs";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { transport } from "../../server";
import { sendError } from "mcp-utils/utils";
import { tools } from "../../utils/constants";
import { PresentationData } from "../../types";
import resolvePath from "../../utils/resolvePath";

export const createPresentation = async (filePath: string, data: PresentationData, options: {
    slideSize?: "standard" | "widescreen";
} = {}) => {
    const fullPath = await resolvePath(filePath, 'write');
    const finalPath = fullPath.endsWith('.pptx') ? fullPath : `${fullPath}.pptx`;
    const parentDir = path.dirname(finalPath);
    await fs.mkdir(parentDir, {recursive: true});

    const pptx = new PptxGenJS();
    pptx.author = data.author || "Generated by MCP";
    pptx.title = data.title;

    if (options.slideSize === "widescreen") {
        pptx.defineLayout({name: "LAYOUT_WIDE", width: 13.33, height: 7.5});
        pptx.layout = "LAYOUT_WIDE";
    }

    for (const [index, slideData] of data.slides.entries()) {
        const slide = pptx.addSlide();

        if (slideData.backgroundColor) {
            slide.background = {color: slideData.backgroundColor.replace('#', '')};
        }

        if (slideData.title) {
            const titleStyle = slideData.titleStyle || {};
            slide.addText(slideData.title, {
                x: 0.5,
                y: 0.5,
                w: "95%",
                h: 1,
                fontSize: titleStyle.fontSize || 32,
                fontFace: titleStyle.fontFace || "Calibri",
                color: titleStyle.color?.replace('#', '') || "000000",
                bold: titleStyle.bold !== false,
                italic: titleStyle.italic || false
            });
        }

        if (slideData.content && slideData.content.length > 0) {
            const startY = slideData.title ? 2 : 1;
            const contentStyle = slideData.contentStyle || {};

            slideData.content.forEach((text, i) => {
                slide.addText(text, {
                    x: 0.5,
                    y: startY + (i * 0.5),
                    w: "95%",
                    h: 0.4,
                    fontSize: contentStyle.fontSize || 18,
                    fontFace: contentStyle.fontFace || "Calibri",
                    color: contentStyle.color?.replace('#', '') || "000000",
                    bold: contentStyle.bold || false,
                    italic: contentStyle.italic || false,
                    bullet: slideData.layout !== "title"
                });
            });
        }
    }

    await pptx.writeFile({fileName: finalPath});
    return `Presentation created successfully: ${path.basename(finalPath)} (${data.slides.length} slides) ✅`;
}

export const registerTool = (server: McpServer) => {
    const toolConfig = tools.createPresentation;
    server.tool(
        toolConfig.name,
        toolConfig.techDescription,
        {
            filePath: z.string().describe(toolConfig.parameters.find(p => p.name === 'filePath')?.techDescription || ''),
            data: z.object({
                title: z.string().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'title')?.techDescription || ''),
                author: z.string().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'author')?.techDescription || ''),
                slides: z.array(z.object({
                    title: z.string().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'title')?.techDescription || ''),
                    titleStyle: z.object({
                        fontSize: z.number().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'titleStyle')?.parameters?.find(tf => tf.name === 'fontSize')?.techDescription || ''),
                        fontFace: z.string().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'titleStyle')?.parameters?.find(tf => tf.name === 'fontFace')?.techDescription || ''),
                        color: z.string().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'titleStyle')?.parameters?.find(tf => tf.name === 'color')?.techDescription || ''),
                        bold: z.boolean().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'titleStyle')?.parameters?.find(tf => tf.name === 'bold')?.techDescription || ''),
                        italic: z.boolean().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'titleStyle')?.parameters?.find(tf => tf.name === 'italic')?.techDescription || ''),
                    }).optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'titleStyle')?.techDescription || ''),
                    content: z.array(z.string()).optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'content')?.techDescription || ''),
                    contentStyle: z.object({
                        fontSize: z.number().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'contentStyle')?.parameters?.find(cf => cf.name === 'fontSize')?.techDescription || ''),
                        fontFace: z.string().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'contentStyle')?.parameters?.find(cf => cf.name === 'fontFace')?.techDescription || ''),
                        color: z.string().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'contentStyle')?.parameters?.find(cf => cf.name === 'color')?.techDescription || ''),
                        bold: z.boolean().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'contentStyle')?.parameters?.find(cf => cf.name === 'bold')?.techDescription || ''),
                        italic: z.boolean().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'contentStyle')?.parameters?.find(cf => cf.name === 'italic')?.techDescription || '')
                    }).optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'contentStyle')?.techDescription || ''),
                    backgroundColor: z.string().optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'backgroundColor')?.techDescription || ''),
                    layout: z.enum(["title", "content", "section", "comparison", "blank"]).optional().describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.parameters?.find(sf => sf.name === 'layout')?.techDescription || ''),
                })).describe(toolConfig.parameters.find(p => p.name === 'data')?.parameters?.find(f => f.name === 'slides')?.techDescription || ''),
            }).describe(toolConfig.parameters.find(p => p.name === 'data')?.techDescription || ''),
            options: z.object({
                slideSize: z.enum(["standard", "widescreen"]).optional().describe(toolConfig.parameters.find(p => p.name === 'options')?.parameters?.find(of => of.name === 'slideSize')?.techDescription || ''),
            }).optional().describe(toolConfig.parameters.find(p => p.name === 'options')?.techDescription || ''),
        },
        async ({filePath, data, options = {}}) => {
            try {
                const result = await createPresentation(filePath, data, options);

                return {
                    content: [
                        {
                            type: "text" as const,
                            text: result,
                        },
                    ],
                };
            } catch (error: any) {
                sendError(transport, new Error(`Failed to create presentation: ${error.message}`), toolConfig.name);
                return {
                    content: [
                        {
                            type: "text" as const,
                            text: `Failed to create presentation ❌: ${error.message}`,
                        },
                    ],
                };
            }
        }
    );
}
