import z from "zod";
import path from "path";
import * as fs from "fs/promises";
import PptxGenJS from "pptxgenjs";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { transport } from "../../server";
import { sendError } from "mcp-utils/utils";
import { tools } from "../../utils/constants";
import resolvePath from "../../utils/resolvePath";

interface SlideContent {
    title?: string;
    titleStyle?: {
        fontSize?: number;
        fontFace?: string;
        color?: string;
        bold?: boolean;
        italic?: boolean;
    };
    content?: string[];
    contentStyle?: {
        fontSize?: number;
        fontFace?: string;
        color?: string;
        bold?: boolean;
        italic?: boolean;
    };
    backgroundColor?: string;
    layout?: "title" | "content" | "section" | "comparison" | "blank";
}

interface PresentationData {
    title: string;
    author?: string;
    slides: SlideContent[];
}

export const createPresentation = async (filePath: string, data: PresentationData, options: {
    slideSize?: "standard" | "widescreen";
} = {}) => {
    const fullPath = await resolvePath(filePath, 'write');
    const finalPath = fullPath.endsWith('.pptx') ? fullPath : `${fullPath}.pptx`;
    const parentDir = path.dirname(finalPath);
    await fs.mkdir(parentDir, {recursive: true});

    const pptx = new PptxGenJS();
    pptx.author = data.author || "Generated by MCP";
    pptx.title = data.title;

    if (options.slideSize === "widescreen") {
        pptx.defineLayout({name: "LAYOUT_WIDE", width: 13.33, height: 7.5});
        pptx.layout = "LAYOUT_WIDE";
    }

    for (const [index, slideData] of data.slides.entries()) {
        const slide = pptx.addSlide();

        if (slideData.backgroundColor) {
            slide.background = {color: slideData.backgroundColor.replace('#', '')};
        }

        if (slideData.title) {
            const titleStyle = slideData.titleStyle || {};
            slide.addText(slideData.title, {
                x: 0.5,
                y: 0.5,
                w: "95%",
                h: 1,
                fontSize: titleStyle.fontSize || 32,
                fontFace: titleStyle.fontFace || "Calibri",
                color: titleStyle.color?.replace('#', '') || "000000",
                bold: titleStyle.bold !== false,
                italic: titleStyle.italic || false
            });
        }

        if (slideData.content && slideData.content.length > 0) {
            const startY = slideData.title ? 2 : 1;
            const contentStyle = slideData.contentStyle || {};

            slideData.content.forEach((text, i) => {
                slide.addText(text, {
                    x: 0.5,
                    y: startY + (i * 0.5),
                    w: "95%",
                    h: 0.4,
                    fontSize: contentStyle.fontSize || 18,
                    fontFace: contentStyle.fontFace || "Calibri",
                    color: contentStyle.color?.replace('#', '') || "000000",
                    bold: contentStyle.bold || false,
                    italic: contentStyle.italic || false,
                    bullet: slideData.layout !== "title"
                });
            });
        }
    }

    await pptx.writeFile({fileName: finalPath});
    return `Presentation created successfully: ${path.basename(finalPath)} (${data.slides.length} slides) ✅`;
}

export const registerTool = (server: McpServer) => {
    server.tool(
        tools.createPresentation,
        "Creates a PowerPoint presentation (.pptx) with specified slides and content",
        {
            filePath: z.string().describe("Absolute or base-relative path to the presentation file (will add .pptx if missing)"),
            data: z.object({
                title: z.string().describe("Presentation title"),
                author: z.string().optional().describe("Author name"),
                slides: z.array(z.object({
                    title: z.string().optional().describe("Slide title"),
                    titleStyle: z.object({
                        fontSize: z.number().optional(),
                        fontFace: z.string().optional(),
                        color: z.string().optional(),
                        bold: z.boolean().optional(),
                        italic: z.boolean().optional()
                    }).optional(),
                    content: z.array(z.string()).optional().describe("Array of text content/bullet points"),
                    contentStyle: z.object({
                        fontSize: z.number().optional(),
                        fontFace: z.string().optional(),
                        color: z.string().optional(),
                        bold: z.boolean().optional(),
                        italic: z.boolean().optional()
                    }).optional(),
                    backgroundColor: z.string().optional().describe("Hex color for slide background"),
                    layout: z.enum(["title", "content", "section", "comparison", "blank"]).optional().describe("Slide layout type"),
                })).describe("Array of slide data"),
            }).describe("Presentation data with title and slides"),
            options: z.object({
                slideSize: z.enum(["standard", "widescreen"]).optional().describe("Slide dimensions"),
            }).optional()
        },
        async ({filePath, data, options = {}}) => {
            try {
                const result = await createPresentation(filePath, data, options);

                return {
                    content: [
                        {
                            type: "text" as const,
                            text: result,
                        },
                    ],
                };
            } catch (error: any) {
                sendError(transport, new Error(`Failed to create presentation: ${error.message}`), tools.createPresentation);
                return {
                    content: [
                        {
                            type: "text" as const,
                            text: `Failed to create presentation ❌: ${error.message}`,
                        },
                    ],
                };
            }
        }
    );
}
